{
  "timestamp": "2025-07-07 17:18:28",
  "level": "ERROR",
  "message": "Uncaught Exception listen EADDRINUSE: address already in use :::3550",
  "stack": "Error: listen EADDRINUSE: address already in use :::3550\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (C:\\Repos\\RestaurantDeveloper\\node_modules\\express\\lib\\application.js:635:24)\n    at Object.<anonymous> (C:\\Repos\\RestaurantDeveloper\\backend\\app.js:94:22)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)",
  "category": "errors",
  "name": "Error"
}
